# Generated by Django 5.1.6 on 2025-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received')], max_length=8),
        ),
    ]
