# Generated by Django 5.1.6 on 2025-03-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
