# Generated by Django 5.1.6 on 2025-03-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_conversation_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
    ]
